version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run: yarn add -D firebase-tools
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application for production
          command: npm run build
      - run:
          name: Deploy app to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
